//
//  PluginManager.cpp
//  Preview3D

// Class that handles loading of plugins.
// To add a new plugin DO NOT EDIT this file but look at PluginInstances.h

#include "PluginManager.h"

_PluginManager_*  __PluginManager_instance;
void CreatePluginManager()
{
	__PluginManager_instance = new _PluginManager_;
}
_PluginManager_& PluginManager()
{
  return *__PluginManager_instance;
}

void DeletePluginManager() {
	delete __PluginManager_instance;
	__PluginManager_instance = 0;
}